### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EmanYm** [rodel77/ModBanner#1]
How does modbanner determine who can use the commands?  Does it run from the server's op file or is there something in the config file to set who can use them?
(I have not installed it to the server yet, but it will be added soon)

Would it be to much trouble to add a few permission nodes for those of us that like to micro-manage access to commands?
My proposal for nodes:
`modbanner.command.add`
`modbanner.command.remove`
add and remove can technically be part of the same permission.  Or they could be replaced with `modbanner.command.manage`

`modbanner.command.list`
`modbanner.command.list.player` (or info.player)
`modbanner.command.list.mods` (or info.mod)

`modbanner.command.reload`

**Comment by rodel77** [comment]
Currently the only permission is "modbanner", but i will try to add more!

**Comment by EmanYm** [comment]
Okay, so there is a node.  Good to know!  Thank you for the swift reply.

**Comment by rodel77** [comment]
Addded for next update!
