### ISSUE TITLE
Wrong version reported and an error during player join

### ISSUE THREAD

**Issue by EmanYm** [rodel77/ModBanner#3]
I got [an error](https://hastebin.com/bubalafike.md) when I joined my server

I thought there was an update, so I downloaded the latest version from the Releases page and checked the mcmod.info.  It does indeed say 1.0.0 in that file, but the Releases page says 1.1.1

SpongeVanilla 5.2.0 B385
ModBanner 1.0.0 (1.1.1)

**Comment by rodel77** [comment]
Sorry dont work to spongevanilla, you need spongeforge

**Comment by EmanYm** [comment]
Alright.  I guess I can just put it on my play server.  Thank you for the reply.
