### ISSUE TITLE
Resource packs and hacked clients?

### ISSUE THREAD

**Issue by EmanYm** [rodel77/ModBanner#4]
Does ModBanner have the capabilities to detect and ban players with resourcepacks or hacked clients?
I have an incomplete list of resource packs, clients and mods.  I know a lot of mods/plugins are reported by vanilla servers, but I'm not sure if all of them are.

Radars
-Gameshark
-Rc-Radar
-PokeRadar

X-Ray Mods and Texture Packs
-XRay Mod
Julialy’s X-Ray Mod
XRay Mod by Omaration
TheSimple Xray Mod
Kradxn’s XRay Mod
Xray Ultimate Resource Pack
StrongestCraft Resource Pack

Hacked Clients
LiquidBouce Client
Wurst 4.2
Wolfram
Wurst 4.1
Impact Client
Huzuni
Carrot
Aristois
Matrix Client
Wizardhax

Other Cheat Hacks/Mods
MassTPA
Panic
CaveFinder
BaseFinder
Phase
JetPack
FreeCam
SpeedHack
YesCheat+
Flight
FullBright
NoClip
Step
Jesus
Spider
HighJump
Blink
AirWalk
VClip
TP
HClip

**Comment by rodel77** [comment]
The only thing this mod detect is mods, you need spongeforge, for connect forge user with server, its impossible detect resource packs or hacked clients (Otherwise server would be clear of hackers)
