### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by EmanYm** [rodel77/ModBanner#5]
Would you consider adding a list of players that are permitted some blocked plugins/mods?
As an example, a client-side plugin that I want my admins to use, but no regular players.

Perhaps even a "greylist" for the above reasons, except it will announce to admins when a someone is found with something on the list.

**Comment by rodel77** [comment]
Sorry for wait time, currently i dont have to much time to update this plugin, but if i can i will add it soon

**Comment by EmanYm** [comment]
Twelve days is not that long.  I've been waiting since December 31, 2013 for a response on another mod I used to use.  Other tickets have been answered, just not the one I posted.

**Comment by rodel77** [comment]
Added in the last update permission modbanner.bypass
