### ISSUE TITLE
[API7]Can't Start up ther server with ModBanner installed

### ISSUE THREAD

**Issue by Tollainmear** [rodel77/ModBanner#8]
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
SpongeForge: 1.12.2-2611-7.1.0-BETA-2931
Minecraft Forge: 14.23.2.2611

ModBanner Version: ModBanner-1.1.2

[Exceptions in gist](https://gist.github.com/Tollainmear/b69e488fdcc5496e6970d74fdf50d13f)

Something like need requires `mod` Forge, but I'm sure that I'm starting a Forged server.

**Comment by rodel77** [comment]
Good report, i will try to replicate it!

**Comment by Tollainmear** [comment]
Waiting in hope XD

**Comment by rodel77** [comment]
I tried to replicate and everything works right, anyway i have removed "Forge" dependency that probably is misspelled, please test the latest version 1.1.3 https://github.com/rodel77/ModBanner/releases/tag/1.1.3

**Comment by Tollainmear** [comment]
whoops.... The release page linked was not contain `.jar`.... just source code there
qwq should I compile it with my IDEA......

**Comment by rodel77** [comment]
Oh my bad... I miss it, try now to download the same release, i uploaded the jar

**Comment by Tollainmear** [comment]
There were a [Exception](https://gist.github.com/Tollainmear/349c530819d4471e4ed09e8c4f9ba1f9) appeared while execute /modbanner list

**Comment by rodel77** [comment]
Probably an issue with API 7, i will check it

**Comment by rodel77** [comment]
Updated to API 7.1.0 https://github.com/rodel77/ModBanner/releases/tag/1.1.5 + i tested it and now everything should work good

**Comment by rodel77** [comment]
Now its working?

**Comment by Tollainmear** [comment]
sorry I will try it now

**Comment by Tollainmear** [comment]
Cool it works well now Thx for supporting~!
And I found that /modbanner could not be complete by `TAB`
aha~ is that command wrongly registed with spongapi ?

**Comment by Tollainmear** [comment]
and I found that /modbanner could not be complete by `TAB`
aha~ is that command wrongly registed with spongapi ?

**Comment by Tollainmear** [comment]
Hi~ Another problem appeared is the message could not be sent to the player's screen while they were kicked by modbanner~ 😅~
the expect thing was to make player notice "You can't use xxx in this server", but there were exception info about `Internal Exception: java.io.IOException : an existing connection was forcibly closed by the remote host`, but there was normally sent the kick message while I type `/kick Tollainmear For-Test`. 

Could that be replicated on your testing server? cause I'm not sure is that a internet problem XD.
Come on dude! almost perfect! 👍
