### ISSUE TITLE
Custom kick message not showing

### ISSUE THREAD

**Issue by ghost** [rodel77/ModBanner#9]
As the title suggests, custom kick messages are not showing when you get kicked from the server for having a disallowed mod. Usually it just displays "Disconnected" rather than the configured message (also with the default message provided by ModBanner).

Versions : 
- spongeforge-1.12.2-2705-7.1.0-BETA-3206 (latest recommended at this time)
- ModBanner-1.1.5

I am of course happy to test to help out, just let me know what you need :v:

**Comment by rodel77** [comment]
That is a known issue, I've tried everything when I found it but unfortunately I can't solve it
